// lib/types.ts — domain-agnostic state shapes. Mirrors the Firestore document
// at users/{uid}. No subject content lives here (that's domain/config.ts).

export type Gap = {
  id: string;
  text: string;
  date: string; // ISO
  resolved: boolean;
};

// An item added to the track from a scan recommendation.
export type CustomItem = {
  id: string;
  cat: string;
  title: string;
  meta: string;
  desc: string;
  url: string;
};

export type QuizStat = { a: number; c: number }; // answered, correct

export type QuizHistoryEntry = {
  date: string;
  score: number;
  total: number;
  mode: string;
};

export type Quiz = {
  stats: Record<string, QuizStat>;
  history: QuizHistoryEntry[];
};

// A validated multiple-choice question generated by the scout.
export type BankQuiz = {
  q: string;
  opts: string[];
  a: number;
  why: string;
};

// A knowledge-bank entry filed from a scan (cap 200, FIFO).
export type BankEntry = {
  id: string;
  t: string; // title
  u: string; // canonical url
  s: string; // summary
  cat: string;
  hash: number; // simhash32(title + " " + summary)
  date: string;
  quiz: BankQuiz | null;
};

// A scout recommendation surfaced to the user (pre-add).
export type Rec = {
  id: string;
  title: string;
  source: string;
  url: string;
  summary: string;
  reasoning: string;
  fit: string;
  category: string;
  priority: "now" | "soon" | "later";
  quiz: BankQuiz | null;
};

export type ScanState = {
  trace: string[]; // grounding queries the model ran
  recs: Rec[];
  date: string | null;
  suppressed: number;
};

export type UserState = {
  done: Record<string, boolean>;
  doneAt: Record<string, string>; // ISO date per completed item id
  gaps: Gap[];
  custom: CustomItem[];
  quiz: Quiz;
  achievements: Record<string, string>; // id -> unlock date
  bank: BankEntry[];
  scan: ScanState;
  // Per-user scout rate-limit bookkeeping (server-enforced).
  scoutMeta?: {
    lastScanAt?: string; // ISO
    dayKey?: string; // YYYY-MM-DD
    dayCount?: number;
  };
};

export function emptyState(): UserState {
  return {
    done: {},
    doneAt: {},
    gaps: [],
    custom: [],
    quiz: { stats: {}, history: [] },
    achievements: {},
    bank: [],
    scan: { trace: [], recs: [], date: null, suppressed: 0 },
    scoutMeta: {},
  };
}
